version: "3"
services:
  api_dev:
    image: robsonroch/api-ts
    ports:
      - "5000:3050"
    links:
      - link-db
  link-db:
    image: tutum/mongodb
    ports:
      - "27010:27010"
      - "28017:28017"
    environment:
      - AUTH=no